import unreal

# READ ONLY. Exact literals behind the slide phase gates and the layer weight: what the comparison
# thresholds are, whether a SlideAlpha getter node already exists, and the phase players' start positions.
AB = '/Game/Variant_Shooter/Tests/LPSP_AR02/ABP_AR02_LPSP_Test'
GRAPH = 'AnimGraph'
SAVED = unreal.Paths.project_saved_dir() + 'LPSP_AR02/'
L = []


def log(m):
    L.append(str(m))


pkg = unreal.load_asset(AB).get_outermost()


def find(name):
    for n in unreal.ObjectIterator(unreal.EdGraphNode):
        try:
            if n.get_outermost() == pkg and n.get_outer() and n.get_outer().get_name() == GRAPH and n.get_name() == name:
                return n
        except Exception:
            pass
    return None


first = True
for nm in ('K2Node_CallFunction_7', 'K2Node_CallFunction_4', 'K2Node_VariableGet_1', 'K2Node_CallFunction_5',
           'K2Node_VariableGet_7', 'AnimGraphNode_BlendListByBool_4', 'AnimGraphNode_BlendListByBool_3'):
    n = find(nm)
    log('')
    if not n:
        log('%s MISSING' % nm)
        continue
    try:
        title = str(n.get_node_title()).replace('\n', ' ')
    except Exception:
        title = '?'
    log('%s [%s]' % (nm, title[:60]))
    for p in n.list_all_pins():
        try:
            name = str(p.get_pin_name())
        except Exception as e:
            log('   pin name err %s' % e)
            continue
        try:
            conn = [x.get_owning_node().get_name() + '.' + str(x.get_pin_name()) for x in p.list_connected_pins()]
        except Exception as e:
            conn = ['ERR %s' % e]
        vals = {}
        for attr in ('default_value', 'default_object', 'autogenerated_default_value'):
            try:
                v = p.get_editor_property(attr)
                try:
                    v = v.get_name()
                except Exception:
                    pass
                vals[attr] = v
            except Exception:
                pass
        log('   %-14s conn=%-44s %s' % (name, str(conn)[:44], vals if vals else ''))
        if first:
            log('      pin attrs: %s' % [a for a in dir(p) if not a.startswith('_')][:45])
            first = False

log('')
log('===== phase players =====')
for nm in ('AnimGraphNode_SequencePlayer_5', 'AnimGraphNode_SequencePlayer_6',
           'AnimGraphNode_SequencePlayer_7', 'AnimGraphNode_SequencePlayer_1'):
    n = find(nm)
    if not n:
        log('%s MISSING' % nm)
        continue
    inner = n.get_editor_property('node')
    for p in ('sequence', 'loop_animation', 'play_rate', 'start_position'):
        try:
            v = inner.get_editor_property(p)
            try:
                v = v.get_name()
            except Exception:
                pass
            log('%-34s %-14s %s' % (nm, p, v))
        except Exception:
            log('%-34s %-14s ERR' % (nm, p))

log('')
log('===== anim instance variables =====')
try:
    ab = unreal.load_asset(AB)
    cdo = unreal.get_default_object(ab.generated_class())
    for v in ('SlideAlpha', 'CrouchAlpha', 'Crouching', 'Jumping', 'Aiming', 'SlideDuration'):
        try:
            log('%-14s %s' % (v, cdo.get_editor_property(v)))
        except Exception as e:
            log('%-14s ERR %s' % (v, str(e)[:60]))
except Exception as e:
    log('anim class ERR %s' % e)

open(SAVED + 'gates_now.txt', 'w', encoding='utf-8').write('\n'.join(L))
print('WROTE gates_now.txt lines=%d' % len(L))
